import type { Locale } from "./i18n";
const keys = ["mode", "hint", "target", "selector", "notConfigured", "notPermitted", "consent", "sensitive", "sourceLimit"] as const;
export type SemanticMessages = Record<(typeof keys)[number], string>;
const labels: Record<Locale, readonly string[]> = {
  en: ["Model-assisted quotations", "The model proposes kind/key labels over exact source quotations; candidates remain pending. Only this source text and fixed instructions are sent. Local fields/paragraph modes never call a provider.", "Reviewed provider target", "Exact source disclosure selector", "No model provider is configured. Use a local extraction mode.", "Authorize this exact selector in the provider policy's document_paths, with the private namespace/labels and matching target. Broad document grants do not authorize learning text.", "Send this exact source text to the reviewed provider for this attempt", "Allow sensitive source text for this attempt", "Maximum source codepoints for the configured model context"],
  "zh-CN": ["模型辅助原文候选", "模型为精确原文片段提出类型/字段建议，候选仍须确认。仅发送本来源原文和固定指令；本地字段/段落模式不调用模型。", "已核对的模型目标", "本来源的精确披露选择器", "尚未配置模型服务，请使用本地提取模式。", "须在披露策略 document_paths 中授权此精确选择器，并允许 private 命名空间/标签及匹配目标；宽泛文档授权不允许发送学习原文。", "本次将这份完整来源原文发送给已核对的模型服务", "本次允许发送敏感来源原文", "当前模型上下文允许的最大来源字符数"],
  "zh-TW": ["模型輔助原文候選", "模型為精確原文片段提出類型/欄位建議，候選仍須確認。只傳送本來源原文與固定指令；本機欄位/段落模式不呼叫模型。", "已核對的模型目標", "本來源的精確揭露選擇器", "尚未設定模型服務，請使用本機擷取模式。", "須在揭露策略 document_paths 授權此精確選擇器，允許 private 命名空間/標籤與相符目標；廣泛文件授權不允許傳送學習原文。", "本次將這份完整來源原文傳送給已核對的模型服務", "本次允許傳送敏感來源原文", "目前模型內容允許的最大來源字元數"],
  ja: ["モデル支援の原文候補", "モデルは正確な引用の種類とキーを提案します。候補は確認待ちです。このソースと固定指示だけを送信し、ローカルモードはモデルを呼びません。", "確認したモデル対象", "このソースの送信セレクター", "モデルは未設定です。ローカル抽出を使ってください。", "private名前空間・ラベルと一致する対象を許可し、document_pathsにこの正確なセレクターを登録してください。包括的な文書許可は学習原文を許可しません。", "この試行でソース全文を確認済みモデルに送信", "この試行で機密の原文を送信", "モデルのコンテキストで許可される最大ソース文字数"],
  ko: ["모델 지원 원문 후보", "모델은 정확한 인용의 유형과 키를 제안합니다. 후보는 확인 대기 상태입니다. 이 출처와 고정 지침만 전송하며 로컬 모드는 모델을 호출하지 않습니다.", "검토된 모델 대상", "이 출처의 전송 선택자", "모델이 설정되지 않았습니다. 로컬 추출을 사용하세요.", "private 네임스페이스·레이블과 일치하는 대상을 허용하고 document_paths에 정확한 선택자를 승인하세요. 광범위한 문서 권한은 학습 원문을 허용하지 않습니다.", "이번 시도에 출처 전체 원문을 검토된 모델에 전송", "이번 시도에 민감한 출처 원문 전송 허용", "모델 컨텍스트에서 허용되는 최대 출처 문자 수"],
  es: ["Citas asistidas por modelo", "El modelo propone tipos y claves sobre citas exactas; los candidatos quedan pendientes. Solo se envían esta fuente e instrucciones fijas. Los modos locales no llaman al modelo.", "Destino de modelo revisado", "Selector exacto de la fuente", "No hay modelo configurado. Usa extracción local.", "Autoriza este selector en document_paths con espacio y etiquetas private y destino coincidente. Un permiso amplio de documentos no autoriza texto de aprendizaje.", "Enviar esta fuente completa al modelo revisado para este intento", "Permitir texto sensible para este intento", "Máximo de caracteres de fuente en el contexto del modelo"],
  fr: ["Citations assistées par modèle", "Le modèle propose types et clés sur des citations exactes ; les candidats restent en attente. Seuls cette source et des instructions fixes sont envoyés. Les modes locaux n’appellent aucun modèle.", "Cible de modèle vérifiée", "Sélecteur exact de la source", "Aucun modèle configuré. Utilisez l’extraction locale.", "Autorisez ce sélecteur dans document_paths avec l’espace et les étiquettes private et une cible correspondante. Une autorisation globale de documents n’autorise pas le texte d’apprentissage.", "Envoyer cette source complète au modèle vérifié pour cet essai", "Autoriser le texte sensible pour cet essai", "Nombre maximal de caractères source dans le contexte du modèle"],
  de: ["Modellgestützte Zitate", "Das Modell schlägt Typen und Schlüssel für exakte Zitate vor; Kandidaten bleiben ungeprüft. Nur diese Quelle und feste Anweisungen werden gesendet. Lokale Modi rufen kein Modell auf.", "Geprüftes Modellziel", "Exakter Quellenselektor", "Kein Modell konfiguriert. Nutze lokale Extraktion.", "Erlaube diesen Selektor in document_paths mit private-Namensraum/-Labels und passendem Ziel. Breite Dokumentfreigaben erlauben keinen Lerntext.", "Diesen vollständigen Quelltext für diesen Versuch an das geprüfte Modell senden", "Sensiblen Quelltext für diesen Versuch erlauben", "Maximale Quellzeichen im Modellkontext"],
  "pt-BR": ["Citações assistidas por modelo", "O modelo propõe tipos e chaves sobre citações exatas; os candidatos ficam pendentes. Somente esta fonte e instruções fixas são enviadas. Modos locais não chamam o modelo.", "Destino do modelo revisado", "Seletor exato da fonte", "Nenhum modelo configurado. Use extração local.", "Autorize este seletor em document_paths com namespace e rótulos private e destino correspondente. Uma autorização ampla de documentos não permite texto de aprendizado.", "Enviar esta fonte completa ao modelo revisado nesta tentativa", "Permitir texto sensível nesta tentativa", "Máximo de caracteres da fonte no contexto do modelo"],
};
export const semanticMessages = Object.fromEntries(Object.entries(labels).map(([locale, values]) => {
  if (values.length !== keys.length) throw new Error(`Incomplete semantic labels: ${locale}`);
  return [locale, Object.fromEntries(keys.map((key, index) => [key, values[index]]))];
})) as Record<Locale, SemanticMessages>;
